import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { AsyncEntry } from "@napi-rs/keyring";
import { Effect, Schema } from "effect";

const CREDENTIAL_REF_PATTERN =
  /^(keychain|credential-manager|secret-service):\/\/.+$/;
const MANAGED_ACCOUNT_CREDENTIAL_RECORD_SCHEMA = Schema.Struct({
  kind: Schema.Literal("managed-session"),
  secret: Schema.String,
  storedAt: Schema.String,
  expiresAt: Schema.NullOr(Schema.String),
});
const LEGACY_MANAGED_ACCOUNT_CREDENTIAL_RECORD_SCHEMA = Schema.Struct({
  kind: Schema.Literal("managed-session"),
  secret: Schema.String,
  storedAt: Schema.String,
});
const ERRNO_CAUSE_SCHEMA = Schema.Struct({
  code: Schema.String,
  message: Schema.optional(Schema.String),
});
const ERROR_WITH_MESSAGE_SCHEMA = Schema.Struct({
  message: Schema.String,
});
const UNKNOWN_RECORD_SCHEMA = Schema.Record(Schema.String, Schema.Unknown);

const isErrnoCause = Schema.is(ERRNO_CAUSE_SCHEMA);
const isErrorWithMessage = Schema.is(ERROR_WITH_MESSAGE_SCHEMA);
const isUnknownRecord = Schema.is(UNKNOWN_RECORD_SCHEMA);
const isManagedAccountCredentialRecord = Schema.is(
  MANAGED_ACCOUNT_CREDENTIAL_RECORD_SCHEMA
);
const isLegacyManagedAccountCredentialRecord = Schema.is(
  LEGACY_MANAGED_ACCOUNT_CREDENTIAL_RECORD_SCHEMA
);

export type SupportedCredentialRefScheme =
  | "keychain"
  | "credential-manager"
  | "secret-service";

export interface ParsedCredentialRef {
  readonly raw: string;
  readonly scheme: SupportedCredentialRefScheme;
  readonly service: string;
  readonly account: string;
  readonly keyringTarget: string;
}

export interface ManagedAccountCredentialRecord {
  readonly kind: "managed-session";
  readonly secret: string;
  readonly storedAt: string;
  readonly expiresAt: string | null;
}

interface CredentialStoreDriver {
  readonly get: (
    ref: ParsedCredentialRef
  ) => Effect.Effect<string | null, DaemonCredentialStoreError>;
  readonly set: (
    ref: ParsedCredentialRef,
    value: string
  ) => Effect.Effect<void, DaemonCredentialStoreError>;
  readonly remove: (
    ref: ParsedCredentialRef
  ) => Effect.Effect<boolean, DaemonCredentialStoreError>;
}

export class DaemonCredentialRefError extends Schema.TaggedErrorClass<DaemonCredentialRefError>()(
  "DaemonCredentialRefError",
  {
    ref: Schema.String,
    message: Schema.String,
    details: Schema.String,
  }
) {}

export class DaemonCredentialStoreError extends Schema.TaggedErrorClass<DaemonCredentialStoreError>()(
  "DaemonCredentialStoreError",
  {
    operation: Schema.String,
    ref: Schema.String,
    message: Schema.String,
    details: Schema.String,
  }
) {}

export class DaemonCredentialRecordError extends Schema.TaggedErrorClass<DaemonCredentialRecordError>()(
  "DaemonCredentialRecordError",
  {
    ref: Schema.String,
    message: Schema.String,
    details: Schema.String,
  }
) {}

export class DaemonCredentialExpiredError extends Schema.TaggedErrorClass<DaemonCredentialExpiredError>()(
  "DaemonCredentialExpiredError",
  {
    ref: Schema.String,
    storedAt: Schema.String,
    expiresAt: Schema.String,
    message: Schema.String,
    details: Schema.String,
  }
) {}

const toCauseMessage = (cause: unknown): string =>
  isErrnoCause(cause) && cause.message
    ? cause.message
    : isErrorWithMessage(cause)
      ? cause.message
      : String(cause);

const toIsoNow = (): string => new Date().toISOString();

const parseInstantMillis = (value: string): number | null => {
  const millis = Date.parse(value);
  return Number.isFinite(millis) ? millis : null;
};

const parseCredentialRefEffect = (ref: string) =>
  Effect.try({
    try: (): ParsedCredentialRef => {
      if (!CREDENTIAL_REF_PATTERN.test(ref)) {
        throw new DaemonCredentialRefError({
          ref,
          message:
            "Credential ref must use keychain://, credential-manager://, or secret-service://.",
          details: "Use a secure credentialRef generated by `ums account add`.",
        });
      }
      const parsed = new URL(ref);
      const scheme = parsed.protocol.slice(
        0,
        -1
      ) as SupportedCredentialRefScheme;
      const service = decodeURIComponent(parsed.hostname).trim();
      const account = decodeURIComponent(
        parsed.pathname.replace(/^\/+/, "")
      ).trim();
      if (!service) {
        throw new DaemonCredentialRefError({
          ref,
          message: "Credential ref must include a non-empty service name.",
          details: "Expected format like keychain://ums/company.",
        });
      }
      if (!account) {
        throw new DaemonCredentialRefError({
          ref,
          message: "Credential ref must include a non-empty account path.",
          details: "Expected format like keychain://ums/company.",
        });
      }
      return {
        raw: ref,
        scheme,
        service,
        account,
        keyringTarget: `ums-${scheme}`,
      };
    },
    catch: (cause) =>
      new DaemonCredentialRefError({
        ref,
        message: "Credential ref is invalid.",
        details: toCauseMessage(cause),
      }),
  });

const createSystemCredentialStoreDriver = (): CredentialStoreDriver => ({
  get: (ref) =>
    Effect.tryPromise({
      try: async () =>
        (await AsyncEntry.withTarget(
          ref.keyringTarget,
          ref.service,
          ref.account
        ).getPassword()) ?? null,
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "get",
          ref: ref.raw,
          message: `Failed to read secure credential '${ref.raw}'.`,
          details: toCauseMessage(cause),
        }),
    }),
  set: (ref, value) =>
    Effect.tryPromise({
      try: async () => {
        await AsyncEntry.withTarget(
          ref.keyringTarget,
          ref.service,
          ref.account
        ).setPassword(value);
      },
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "set",
          ref: ref.raw,
          message: `Failed to store secure credential '${ref.raw}'.`,
          details: toCauseMessage(cause),
        }),
    }),
  remove: (ref) =>
    Effect.tryPromise({
      try: () =>
        AsyncEntry.withTarget(
          ref.keyringTarget,
          ref.service,
          ref.account
        ).deleteCredential(),
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "remove",
          ref: ref.raw,
          message: `Failed to delete secure credential '${ref.raw}'.`,
          details: toCauseMessage(cause),
        }),
    }),
});

const readTestCredentialStoreEffect = (
  storeFile: string
): Effect.Effect<Record<string, unknown>, DaemonCredentialStoreError> =>
  Effect.matchEffect(
    Effect.tryPromise({
      try: () => readFile(storeFile, "utf8"),
      catch: (cause) => cause,
    }),
    {
      onSuccess: (raw) =>
        Effect.try({
          try: () => {
            const parsed = JSON.parse(raw);
            return isUnknownRecord(parsed) ? parsed : {};
          },
          catch: (cause) =>
            new DaemonCredentialStoreError({
              operation: "parse-test-store",
              ref: storeFile,
              message: `Failed to parse credential test store '${storeFile}'.`,
              details: toCauseMessage(cause),
            }),
        }),
      onFailure: (cause) =>
        isErrnoCause(cause) && cause.code === "ENOENT"
          ? Effect.succeed({})
          : Effect.fail(
              new DaemonCredentialStoreError({
                operation: "read-test-store",
                ref: storeFile,
                message: `Failed to read credential test store '${storeFile}'.`,
                details: toCauseMessage(cause),
              })
            ),
    }
  );

const writeTestCredentialStoreEffect = (
  storeFile: string,
  payload: Record<string, unknown>
) => {
  const tempFile = `${storeFile}.${process.pid}.${Date.now()}.tmp`;
  return Effect.gen(function* () {
    yield* Effect.tryPromise({
      try: () => mkdir(dirname(storeFile), { recursive: true }),
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "mkdir-test-store",
          ref: storeFile,
          message: `Failed to create credential test store directory for '${storeFile}'.`,
          details: toCauseMessage(cause),
        }),
    });
    yield* Effect.tryPromise({
      try: () =>
        writeFile(tempFile, `${JSON.stringify(payload, null, 2)}\n`, "utf8"),
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "write-test-store",
          ref: storeFile,
          message: `Failed to write credential test store '${storeFile}'.`,
          details: toCauseMessage(cause),
        }),
    });
    yield* Effect.tryPromise({
      try: () => rename(tempFile, storeFile),
      catch: (cause) =>
        new DaemonCredentialStoreError({
          operation: "rename-test-store",
          ref: storeFile,
          message: `Failed to finalize credential test store '${storeFile}'.`,
          details: toCauseMessage(cause),
        }),
    });
    yield* Effect.orElseSucceed(
      Effect.tryPromise({
        try: () => rm(tempFile, { force: true }),
        catch: (cause) =>
          new DaemonCredentialStoreError({
            operation: "cleanup-test-store",
            ref: storeFile,
            message: `Failed to clean up credential test store temp file '${tempFile}'.`,
            details: toCauseMessage(cause),
          }),
      }),
      () => false
    );
  });
};

const createTestCredentialStoreDriver = (
  storeFile: string
): CredentialStoreDriver => {
  const keyFor = (ref: ParsedCredentialRef): string =>
    `${ref.keyringTarget}|${ref.service}|${ref.account}`;
  return {
    get: (ref) =>
      readTestCredentialStoreEffect(storeFile).pipe(
        Effect.map((entries) => {
          const stored = entries[keyFor(ref)];
          return isStringRecordValue(stored) ? stored : null;
        })
      ),
    set: (ref, value) =>
      readTestCredentialStoreEffect(storeFile).pipe(
        Effect.flatMap((entries) =>
          writeTestCredentialStoreEffect(storeFile, {
            ...entries,
            [keyFor(ref)]: value,
          })
        )
      ),
    remove: (ref) =>
      readTestCredentialStoreEffect(storeFile).pipe(
        Effect.flatMap((entries) => {
          if (!(keyFor(ref) in entries)) {
            return Effect.succeed(false);
          }
          const targetKey = keyFor(ref);
          const nextEntries = Object.fromEntries(
            Object.entries(entries).filter(
              ([entryKey]) => entryKey !== targetKey
            )
          );
          return writeTestCredentialStoreEffect(storeFile, nextEntries).pipe(
            Effect.as(true)
          );
        })
      ),
  };
};

const isStringRecordValue = (value: unknown): value is string =>
  Schema.is(Schema.String)(value);

const allowPlaintextTestCredentialStore = (): boolean =>
  process.env["UMS_ALLOW_PLAINTEXT_TEST_CREDENTIAL_STORE"] === "true";

const selectCredentialStoreDriver = (): CredentialStoreDriver => {
  const testStoreFile = process.env["UMS_TEST_CREDENTIAL_STORE_FILE"];
  return testStoreFile && allowPlaintextTestCredentialStore()
    ? createTestCredentialStoreDriver(resolve(testStoreFile))
    : createSystemCredentialStoreDriver();
};

const encodeCredentialRecord = (
  secret: string,
  storedAt = toIsoNow(),
  expiresAt: string | null = null
): string =>
  JSON.stringify({
    kind: "managed-session",
    secret,
    storedAt,
    expiresAt,
  } satisfies ManagedAccountCredentialRecord);

const normalizeCredentialRecord = (
  ref: ParsedCredentialRef,
  raw: unknown
): ManagedAccountCredentialRecord => {
  const parsed = isManagedAccountCredentialRecord(raw)
    ? raw
    : isLegacyManagedAccountCredentialRecord(raw)
      ? {
          ...raw,
          expiresAt: null,
        }
      : null;

  if (parsed === null) {
    throw new DaemonCredentialRecordError({
      ref: ref.raw,
      message: `Stored credential '${ref.raw}' is invalid.`,
      details:
        "Expected a managed-session record with secret, storedAt, and optional expiresAt fields.",
    });
  }
  if (parseInstantMillis(parsed.storedAt) === null) {
    throw new DaemonCredentialRecordError({
      ref: ref.raw,
      message: `Stored credential '${ref.raw}' has an invalid storedAt timestamp.`,
      details: "storedAt must be a valid ISO-8601 timestamp.",
    });
  }
  if (
    parsed.expiresAt !== null &&
    parseInstantMillis(parsed.expiresAt) === null
  ) {
    throw new DaemonCredentialRecordError({
      ref: ref.raw,
      message: `Stored credential '${ref.raw}' has an invalid expiresAt timestamp.`,
      details: "expiresAt must be null or a valid ISO-8601 timestamp.",
    });
  }
  return parsed;
};

const decodeCredentialRecordEffect = (ref: ParsedCredentialRef, raw: string) =>
  Effect.try({
    try: () => normalizeCredentialRecord(ref, JSON.parse(raw)),
    catch: (cause) =>
      cause instanceof DaemonCredentialRecordError
        ? cause
        : new DaemonCredentialRecordError({
            ref: ref.raw,
            message: `Stored credential '${ref.raw}' is invalid.`,
            details: toCauseMessage(cause),
          }),
  });

const validateTimestampInput = (
  ref: ParsedCredentialRef,
  field: "storedAt" | "expiresAt",
  value: string
): Effect.Effect<string, DaemonCredentialRecordError> =>
  parseInstantMillis(value) !== null
    ? Effect.succeed(value)
    : Effect.fail(
        new DaemonCredentialRecordError({
          ref: ref.raw,
          message: `Managed credential ${field} is invalid for '${ref.raw}'.`,
          details: `${field} must be a valid ISO-8601 timestamp.`,
        })
      );

const readManagedAccountCredentialRecordEffect = (credentialRef: string) =>
  parseCredentialRefEffect(credentialRef).pipe(
    Effect.flatMap((ref) =>
      selectCredentialStoreDriver()
        .get(ref)
        .pipe(
          Effect.flatMap((raw) =>
            raw === null
              ? Effect.succeed(null)
              : decodeCredentialRecordEffect(ref, raw).pipe(
                  Effect.map(
                    (record) => record as ManagedAccountCredentialRecord
                  )
                )
          )
        )
    )
  );

const ensureManagedAccountCredentialIsFreshEffect = (
  ref: ParsedCredentialRef,
  record: ManagedAccountCredentialRecord
) => {
  if (record.expiresAt === null) {
    return Effect.succeed(record);
  }
  const expiresAtMillis = parseInstantMillis(record.expiresAt);
  return expiresAtMillis !== null && expiresAtMillis > Date.now()
    ? Effect.succeed(record)
    : Effect.fail(
        new DaemonCredentialExpiredError({
          ref: ref.raw,
          storedAt: record.storedAt,
          expiresAt: record.expiresAt,
          message: `Stored credential '${ref.raw}' expired at ${record.expiresAt}.`,
          details:
            "Run `ums account login` again to refresh secure managed session material.",
        })
      );
};

export const defaultCredentialRefForAccount = (alias: string): string =>
  process.platform === "win32"
    ? `credential-manager://ums/${alias}`
    : process.platform === "linux"
      ? `secret-service://ums/${alias}`
      : `keychain://ums/${alias}`;

export const storeManagedAccountCredential = (input: {
  readonly credentialRef: string;
  readonly secret: string;
  readonly storedAt?: string;
  readonly expiresAt?: string | null;
}) =>
  parseCredentialRefEffect(input.credentialRef).pipe(
    Effect.flatMap((ref) =>
      Effect.gen(function* () {
        const storedAt = yield* validateTimestampInput(
          ref,
          "storedAt",
          input.storedAt ?? toIsoNow()
        );
        const expiresAt =
          input.expiresAt == null
            ? null
            : yield* validateTimestampInput(ref, "expiresAt", input.expiresAt);
        yield* selectCredentialStoreDriver().set(
          ref,
          encodeCredentialRecord(input.secret, storedAt, expiresAt)
        );
      })
    )
  );

export const loadManagedAccountCredential = (credentialRef: string) =>
  readManagedAccountCredentialRecordEffect(credentialRef).pipe(
    Effect.flatMap((record) =>
      record === null
        ? Effect.succeed(null)
        : parseCredentialRefEffect(credentialRef).pipe(
            Effect.flatMap((ref) =>
              ensureManagedAccountCredentialIsFreshEffect(ref, record)
            )
          )
    )
  );

export const deleteManagedAccountCredential = (credentialRef: string) =>
  parseCredentialRefEffect(credentialRef).pipe(
    Effect.flatMap((ref) => selectCredentialStoreDriver().remove(ref))
  );

export const getManagedAccountCredentialState = (credentialRef: string) =>
  readManagedAccountCredentialRecordEffect(credentialRef).pipe(
    Effect.map((record) => {
      if (record === null) {
        return {
          status: "missing" as const,
          storedAt: null,
          expiresAt: null,
        };
      }
      const expiresAtMillis =
        record.expiresAt === null ? null : parseInstantMillis(record.expiresAt);
      return expiresAtMillis !== null && expiresAtMillis <= Date.now()
        ? {
            status: "expired" as const,
            storedAt: record.storedAt,
            expiresAt: record.expiresAt,
          }
        : {
            status: "present" as const,
            storedAt: record.storedAt,
            expiresAt: record.expiresAt,
          };
    }),
    Effect.catchTags({
      DaemonCredentialStoreError: (error) =>
        Effect.succeed({
          status: "error" as const,
          storedAt: null,
          expiresAt: null,
          message: error.message,
        }),
      DaemonCredentialRecordError: (error) =>
        Effect.succeed({
          status: "error" as const,
          storedAt: null,
          expiresAt: null,
          message: error.message,
        }),
      DaemonCredentialRefError: (error) =>
        Effect.succeed({
          status: "error" as const,
          storedAt: null,
          expiresAt: null,
          message: error.message,
        }),
    })
  );
